services:
  wiremock:
    image: wiremock/wiremock:latest
    command: --port 8080 --verbose
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    environment:
      WIREMOCK_OPTIONS: "--verbose"